version: 2
jobs:
  build:
    docker:
      - image: docker:18.06.0-ce-git

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Build Docker
          command: |
            docker build \
              -t gcr.io/gymio-220023/$CIRCLE_PROJECT_REPONAME:$CIRCLE_PROJECT_USERNAME-$CIRCLE_BRANCH \
              -f build/Dockerfile \
              .
