version: 2
jobs:
  build:
    docker:
      - image: docker:18.06.0-ce-git

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Auth Google Cloud k8s
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            sudo gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            sudo gcloud gcloud container clusters get-credentials gymio-cluster

      - run:
          name: Build Docker
          command: |
            docker build \
              -t gcr.io/gymio-220023/$CIRCLE_PROJECT_REPONAME:$CIRCLE_PROJECT_USERNAME-$CIRCLE_BRANCH \
              -t gcr.io/gymio-220023/$CIRCLE_PROJECT_REPONAME:$CIRCLE_PROJECT_USERNAME-$CIRCLE_BRANCH-$CIRCLE_SHA1 \
              -f build/Dockerfile \
              .
